### ISSUE TITLE
Server crash when interacting with villagers

### ISSUE THREAD

**Issue by mimi-min** [Gremlite/MinecraftMod-OurVillagerDiscounts#2]
When Discounts is installed on the server, interacting with any villager will cause the server to crash.

Console log: https://pastebin.com/RJq8jj1c
Crash log; https://pastebin.com/YZH0QEhB

**Comment by Gremlite** [comment]
Thanks for the detail, I'll take a look!

**Comment by Gremlite** [comment]
Not sure how the release action didn't catch that, should've failed compilation the first time around. But I've manually confirmed that the latest build works in a standalone instance with v41.1.0 of the Forge launcher.

The new 1.19 Forge build is [up on CurseForge](https://www.curseforge.com/minecraft/mc-mods/our-villager-discounts/files/3933900).

Let me know if that solves the issue for you!

**Comment by mimi-min** [comment]
It does indeed, thank you!
