### ISSUE TITLE
Curing the villager multiple times does not decrease the prices for all players

### ISSUE THREAD

**Issue by domardomar** [Gremlite/MinecraftMod-OurVillagerDiscounts#3]
**Steps to reproduce:**
1 -> Player A zombifies and cures the villager for the first time - all players receive a discount.
2 -> Player A zombifies and cures the villager again.

**Result:**
Only Player A receives additional discount after repeated curing process. Other players on the server still have the same price from point 1 in "steps to preproduce".

**Expected behaviour:**
All players on the server would have the same price, no matter how many times the villager is cured.

**Version:**
Release v1.19.2+build.0 for Fabric

No other mods affecting the Villager trades are installed on the server.
Example was done using a Cartographer Villager, we looked specifically at the Glass Pane trade.
Server is running Fabric 0.14.9

**Comment by Gremlite** [comment]
Hey! Thanks for cutting the issue.

I have attached a version which should fix the issue. I will try and confirm it myself within the next week or so, but if you can confirm this fixes it, then I'll commit the fix and put it up on CurseForge.

~[our-villager-discounts-1.19.2+build.0.zip](https://github.com/Gremlite/MinecraftMod-OurVillagerDiscounts/files/9739340/our-villager-discounts-1.19.2%2Bbuild.0.zip)~

EDIT: The above upload does not fix the issue, but I have just committed the actual fix for the issue. I will start the release process for v1.19.2+build.1.

**Comment by Gremlite** [comment]
I have confirmed this doesn't work. I'll take a look at this. Seems like the bug that prompted this mod in the first place is causing this issue.

**Comment by Gremlite** [comment]
I have cut a separate issue to backfill the fix to the other Fabric versions. Please reopen the issue if this does not fix it for you!
